-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_settings (
  id text NOT NULL DEFAULT 'default'::text,
  region text DEFAULT 'eu'::text,
  units text DEFAULT 'metric'::text,
  notifications_enabled boolean DEFAULT true,
  data_source text DEFAULT 'telemetry'::text,
  polling_driving integer DEFAULT 30,
  polling_charging integer DEFAULT 60,
  polling_parked integer DEFAULT 300,
  polling_sleeping integer DEFAULT 600,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  home_latitude double precision,
  home_longitude double precision,
  home_address text,
  currency text DEFAULT 'CHF'::text,
  date_format text DEFAULT 'DD/MM'::text,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.charging_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vehicle_id uuid NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  start_battery_pct double precision,
  end_battery_pct double precision,
  energy_added_kwh double precision,
  charge_rate_kw double precision,
  latitude double precision,
  longitude double precision,
  location_name text,
  charger_type text,
  cost_estimate double precision,
  is_complete boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  cost_user_entered double precision,
  currency text DEFAULT 'CHF'::text,
  CONSTRAINT charging_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT charging_sessions_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vehicle_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.polling_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vehicle_id uuid NOT NULL UNIQUE,
  driving_interval_sec integer DEFAULT 30,
  charging_interval_sec integer DEFAULT 300,
  parked_interval_sec integer DEFAULT 1800,
  sleeping_interval_sec integer DEFAULT 3600,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT polling_settings_pkey PRIMARY KEY (id),
  CONSTRAINT polling_settings_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  units text DEFAULT 'imperial'::text CHECK (units = ANY (ARRAY['imperial'::text, 'metric'::text])),
  region text DEFAULT 'eu'::text CHECK (region = ANY (ARRAY['na'::text, 'eu'::text, 'cn'::text])),
  notifications_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.telemetry_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vehicle_id text NOT NULL,
  trip_id uuid,
  event_type text NOT NULL,
  event_data jsonb,
  latitude numeric,
  longitude numeric,
  speed numeric,
  battery_level integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT telemetry_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.telemetry_raw (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  vin text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  payload jsonb NOT NULL,
  CONSTRAINT telemetry_raw_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trip_waypoints (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  speed_mph double precision,
  battery_level integer,
  odometer double precision,
  heading integer,
  CONSTRAINT trip_waypoints_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vin text NOT NULL,
  vehicle_id text,
  start_time timestamp with time zone NOT NULL DEFAULT now(),
  end_time timestamp with time zone,
  is_complete boolean DEFAULT false,
  start_latitude numeric,
  start_longitude numeric,
  start_address text,
  end_latitude numeric,
  end_longitude numeric,
  end_address text,
  start_odometer numeric,
  end_odometer numeric,
  start_battery_pct numeric,
  end_battery_pct numeric,
  distance_miles numeric,
  energy_used_kwh numeric,
  max_speed_mph numeric,
  avg_speed_mph numeric,
  min_outside_temp numeric,
  max_outside_temp numeric,
  avg_outside_temp numeric,
  CONSTRAINT trips_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_settings (
  user_id uuid NOT NULL,
  polling_driving integer DEFAULT 30,
  polling_charging integer DEFAULT 300,
  polling_parked integer DEFAULT 1800,
  polling_sleeping integer DEFAULT 3600,
  region text DEFAULT 'eu'::text CHECK (region = ANY (ARRAY['na'::text, 'eu'::text, 'cn'::text])),
  units text DEFAULT 'imperial'::text CHECK (units = ANY (ARRAY['imperial'::text, 'metric'::text])),
  notifications_enabled boolean DEFAULT true,
  data_source text DEFAULT 'telemetry'::text CHECK (data_source = ANY (ARRAY['polling'::text, 'telemetry'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_settings_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vehicle_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vehicle_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  state text,
  battery_level integer,
  battery_range double precision,
  charging_state text,
  charge_limit_soc integer,
  latitude double precision,
  longitude double precision,
  odometer double precision,
  inside_temp double precision,
  outside_temp double precision,
  is_climate_on boolean,
  shift_state text,
  speed double precision,
  CONSTRAINT vehicle_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_snapshots_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id)
);
CREATE TABLE public.vehicle_status (
  vin text NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  shift_state text,
  speed numeric,
  odometer numeric,
  battery_level numeric,
  lat numeric,
  lon numeric,
  inside_temp numeric,
  outside_temp numeric,
  is_locked boolean,
  current_trip_id uuid,
  trip_start_battery numeric,
  trip_start_odometer numeric,
  sentry_mode boolean,
  charge_state text,
  charger_power numeric,
  is_climate_on boolean,
  car_version text,
  door_df boolean DEFAULT false,
  door_dr boolean DEFAULT false,
  door_pf boolean DEFAULT false,
  door_pr boolean DEFAULT false,
  trunk_ft boolean DEFAULT false,
  trunk_rt boolean DEFAULT false,
  tpms_fl numeric,
  tpms_fr numeric,
  tpms_rl numeric,
  tpms_rr numeric,
  est_battery_range numeric,
  charge_energy_added numeric,
  time_to_full_charge numeric,
  heading numeric,
  rated_range numeric,
  window_fd text,
  window_fp text,
  window_rd text,
  window_rp text,
  home_address text,
  current_charging_session_id uuid,
  home_latitude numeric,
  home_longitude numeric,
  CONSTRAINT vehicle_status_pkey PRIMARY KEY (vin)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  tesla_id text NOT NULL,
  vin text NOT NULL,
  display_name text,
  access_token_encrypted text,
  refresh_token_encrypted text,
  token_expires_at timestamp with time zone,
  region text DEFAULT 'eu'::text CHECK (region = ANY (ARRAY['na'::text, 'eu'::text, 'cn'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.tesla_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_token_hash text NOT NULL UNIQUE,
  access_token_encrypted text NOT NULL,
  refresh_token_encrypted text,
  token_expires_at timestamp with time zone,
  region text NOT NULL DEFAULT 'eu'::text CHECK (region = ANY (ARRAY['na'::text, 'eu'::text, 'cn'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tesla_sessions_pkey PRIMARY KEY (id)
);
